apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-service
    tier: service
    environment: wordpress
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-app
    tier: db
    environment: wordpress
  type: ClusterIP
status:
  loadBalancer: {}
