apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-app
    environment: wordpress
    tier: app
  name: wordpress-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: wordpress-app
    environment: wordpress
    tier: app
  type: NodePort
status:
  loadBalancer: {}
