apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-service
    tier: service
    environment: wordpress
  name: wordpress-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-app
    tier: app
    environment: wordpress
  type: ClusterIP
status:
  loadBalancer: {}
