apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress-mysql
  labels:
    type: pv-wordpress-mysql
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/eroesas/PersistentVolumes/Volumes/mysql"
