apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress-app
  labels:
    type: pv-wordpress-app
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/eroesas/PersistentVolumes/Volumes/wordpress"
