apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tudemo-service
  name: tudemo-service
  namespace: tudemo
spec:
  ports:
  - name: 80-80
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tudemo-deployment
  type: NodePort
status:
  loadBalancer: {}
