apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: balance-api-service
  name: balance-api-service
spec:
  ports:
  - name: 80-3000
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: balance-api-app
  type: NodePort
status:
  loadBalancer: {}
