apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customer-api-app
  name: customer-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customer-api-app
    spec:
      containers:
      - image: swarmgs/customer
        name: customer-api-container
        resources: {}
status: {}
