apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: tinte
spec:
  groups:
    - system:authenticated
  usages:
    - client auth
  request:
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZkR2x1ZEdVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFESTczc1g0Y0JQZE9lK3BmcHA5ZmpPL09lWUJEdXcyMDREaWVIelM0dTViWUh5Ci9kTTZrYzJvRVJqWjFScURYVTBaNzBTS01odldXMEhCdWg5TGY1dXRjSHI3cUNpM1JWeVhQMTZhNDFscXlBWkoKcitWRmswak9SSGU2SFRZSlRmOXVJcUI5OTZNeGhrZHdDdExXMGFPclEvc2tzNURBQ1NNYmZmemVpeDNkR3ZweAo5K0lVdWNCK2oyNEhnTks3Qk9zQklieUdTYld1TGRyL2swVkpiejBXU1k2cHBqNzBxbDVSZlJIcmtaV0FJTVdVCjI3My95c2RLa3lRaFpiRzRwWVQ0VThLUkp1RnJJU2Q3SWxWUXZycDF4Mmc0UnZ3TTVWdW5TbmFJSXN4WjVuU1EKL1ptNHJnWnQ3UEdzMVU4STZ4V1NhRW1UUHVLMnZMTWJKM3dpMVJmREFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFOY0UzVXJkZVBDQ2g5SExnYWhzOHd1eFBrMG1Lbm40eWl5UXd3VFFrMXpWRlpoemIrMTJPClM3M1JnZ0RwVnRZVFh1eDZIOStYNTJPSDJMSGNkOUVwREt0SnB1VDdKVk9NSXVoQkZqRWlXak8vN2NoYUJ6RmoKaG9IaFVkRzl1aTB0QkdSOVE3U1ZvZFdtbEtlV1VwVEh1blM0Snc5Unp4bXo3UWltYUo2cjJubXJWN1hsRHZkSAp5L3UzdFZVVEphNFFmd2N5UFVqVzRCOG5uMXJuZWxUbUZzbUp3RXlPaDZ3bXpOK2JzNm4vM2crdFpUOS9rSElzCkErSzhhNGkvOTUvSGJiTlQvOHE3TFhWQUt5MHVFeGlSRDFCdVhPdjZyYWYrdzkzeUhNYXozSngwOWJJbmpQL0oKaWN6dzB4VTFsNGZpcU5JTFdkRTk5dEM2T0s3OFpRK1hvUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
