apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tudemo-service
  name: tudemo-service
spec:
  ports:
  - name: 8080-80
    nodePort: 30020
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: tudemo
  type: NodePort
status:
  loadBalancer: {}
