apiVersion: v1
kind: ConfigMap
metadata:
  name: balance-api-properties
data:
  MYWEB_CUSTOMER_API: customer-api-service.default.svc.cluster.local:3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customer-api-app
  name: customer-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customer-api-app
    spec:
      containers:
      - image: swarmgs/customer
        name: customer-api-container
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customer-api-service
  name: customer-api-service
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: customer-api-app
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: balance-api-app
  name: balance-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-api-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: balance-api-app
        role: frontend
    spec:
      containers:
      - image: swarmgs/balance
        name: balance-api-container
        envFrom:
          - configMapRef:
              name: balance-api-properties
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: balance-api-service
  name: balance-api-service
spec:
  ports:
  - name: 80-3000
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: balance-api-app
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: customer-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: customer-api-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
    ports:
    - protocol: TCP
      port: 3000
