apiVersion: v1
kind: ReplicationController
metadata:
        name: myapp-rc
        labels: 
                app: amyapp
                type: front-end
spec:
        template: 
                metadata:
                        name: nginx
                        labels:
                                app: nginx-pod
                                type: front-end

                spec: 
                        containers:
                                - name: nginx-container
                                  image: nginx
        replicas: 3
