apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-policy-allow
  namespace: wordpress
spec:
  podSelector:
    matchLabels:
      app: mysql-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: wordpress-app
    ports:
    - protocol: TCP
      port: 3306
