apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress-mysql
  namespace: wordpress
  labels:
    type: pv-wordpress-mysql
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/Apps/Wordpress/Volumes/mysql"
