apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress-mysql
  namespace: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
