apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-app
  name: wordpress-app
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress-app
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-service.wordpress.svc.cluster.local
          - name: WORDPRESS_DB_USER
            value: wordpress-user
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress-passwd
          - name: WORDPRESS_DB_NAME
            value: wordpress-db
          - name: WORDPRESS_TABLE_PREFIX
            value: wp_
      nodeSelector:
        preferred: app  
