apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu-secret
  name: ubuntu-secret
spec:
  containers:
  - image: ubuntu:latest
    name: ubuntu-secret
    command: [ "bash", "-c" ]
    args: [ "while true; do echo $PASSUBUN; sleep 3; done" ] 
    envFrom:
      - secretRef:
              name: passubuntu-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
